<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-11T15:39:49 IST" name="All Test Suite" finished-at="2022-08-11T15:39:57 IST" duration-ms="7938">
    <groups>
    </groups>
    <test started-at="2022-08-11T15:39:49 IST" name="C:/Users/admin/IdeaProjects/RestAssuredAPITesting" finished-at="2022-08-11T15:39:57 IST" duration-ms="7938">
      <class name="Framework_TestCases.TestCases">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:47 IST" name="setUp" finished-at="2022-08-11T15:39:49 IST" duration-ms="1892" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="checkingCreateCustomerAPIwithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:51 IST" name="checkingCreateCustomerAPIwithInvalidSecretKey" data-provider="sendData" finished-at="2022-08-11T15:39:56 IST" duration-ms="4651" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rahul@training.com, name=InvalidNikhil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at Framework_TestCases.TestCases.checkingCreateCustomerAPIwithInvalidSecretKey(TestCases.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingCreateCustomerAPIwithInvalidSecretKey -->
        <test-method signature="checkingCreateCustomerAPIwithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:51 IST" name="checkingCreateCustomerAPIwithInvalidSecretKey" data-provider="sendData" finished-at="2022-08-11T15:39:56 IST" duration-ms="4651" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rahul@training.com, name=InvalidRaj}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at Framework_TestCases.TestCases.checkingCreateCustomerAPIwithInvalidSecretKey(TestCases.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingCreateCustomerAPIwithInvalidSecretKey -->
        <test-method signature="checkingCreateCustomerAPIwithValidSecretKey(java.util.Hashtable)[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:56 IST" name="checkingCreateCustomerAPIwithValidSecretKey" data-provider="sendData" finished-at="2022-08-11T15:39:57 IST" duration-ms="1282" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rahul@training.com, name=Raj, desc=This is framwork creation}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingCreateCustomerAPIwithValidSecretKey -->
        <test-method signature="checkingCreateCustomerAPIwithValidSecretKey(java.util.Hashtable)[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:56 IST" name="checkingCreateCustomerAPIwithValidSecretKey" data-provider="sendData" finished-at="2022-08-11T15:39:57 IST" duration-ms="1275" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rahul@training.com, name=Nikhil, desc=This is framwork creation}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingCreateCustomerAPIwithValidSecretKey -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Framework_TestCases.TestCases@505fc5a4]" started-at="2022-08-11T15:39:58 IST" name="teardown" finished-at="2022-08-11T15:39:58 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Framework_TestCases.TestCases -->
    </test> <!-- C:/Users/admin/IdeaProjects/RestAssuredAPITesting -->
  </suite> <!-- All Test Suite -->
</testng-results>
